## Pandas 总结

- DataFrame 可以理解成一张表；
- 每一行通常表示一条样本；
- 每一列通常表示一个特征；
- `head()` 可以查看前几行；
- `describe()` 可以查看统计信息；
- `df[df["score"] > 80]` 可以筛选数据；
- `sort_values()` 可以排序；
- `groupby()` 可以分组统计；
- `to_csv()` 和 `read_csv()` 可以保存和读取 CSV 文件；
- `isnull()` 和 `fillna()` 可以处理缺失值。

In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [2]:
data = {
    "name": ["Tom", "Jerry", "Alice", "Bob", "Mike", "Lucy"],
    "gender": ["male", "male", "female", "male", "male", "female"],
    "score": [85, 90, 78, 92, 66, 88],
    "study_hours": [5, 6, 3, 7, 2, 6],
}

df = pd.DataFrame(data)

df

    name  gender  score  study_hours
0    Tom    male     85            5
1  Jerry    male     90            6
2  Alice  female     78            3
3    Bob    male     92            7
4   Mike    male     66            2
5   Lucy  female     88            6

In [3]:
print("前 5 行:")
display(df.head())

print("数据形状:")
print(df.shape)

print("列名:")
print(df.columns)

print("数据类型:")
print(df.dtypes)

前 5 行:

    name  gender  score  study_hours
0    Tom    male     85            5
1  Jerry    male     90            6
2  Alice  female     78            3
3    Bob    male     92            7
4   Mike    male     66            2

数据形状:
(6, 4)
列名:
Index(['name', 'gender', 'score', 'study_hours'], dtype='object')
数据类型:
name           object
gender         object
score           int64
study_hours     int64
dtype: object

In [4]:
df.describe()

           score  study_hours
count   6.000000     6.000000
mean   83.166667     4.833333
std     9.724539     1.940790
min    66.000000     2.000000
25%    79.750000     3.500000
50%    86.500000     5.500000
75%    89.500000     6.000000
max    92.000000     7.000000

In [5]:
names = df["name"]
scores = df["score"]

print("姓名:")
print(names)

print("分数:")
print(scores)

姓名:
0      Tom
1    Jerry
2    Alice
3      Bob
4     Mike
5     Lucy
Name: name, dtype: object
分数:
0    85
1    90
2    78
3    92
4    66
5    88
Name: score, dtype: int64

In [6]:
high_score_students = df[df["score"] >= 85]

high_score_students

    name  gender  score  study_hours
0    Tom    male     85            5
1  Jerry    male     90            6
3    Bob    male     92            7
5   Lucy  female     88            6

In [7]:
result = df[(df["score"] >= 85) & (df["study_hours"] >= 5)]

result

    name  gender  score  study_hours
0    Tom    male     85            5
1  Jerry    male     90            6
3    Bob    male     92            7
5   Lucy  female     88            6

In [8]:
df_sorted = df.sort_values(by="score", ascending=False)

df_sorted

    name  gender  score  study_hours
3    Bob    male     92            7
1  Jerry    male     90            6
5   Lucy  female     88            6
0    Tom    male     85            5
2  Alice  female     78            3
4   Mike    male     66            2

In [9]:
df["passed"] = df["score"] >= 60

df

    name  gender  score  study_hours  passed
0    Tom    male     85            5    True
1  Jerry    male     90            6    True
2  Alice  female     78            3    True
3    Bob    male     92            7    True
4   Mike    male     66            2    True
5   Lucy  female     88            6    True

In [10]:
gender_score_mean = df.groupby("gender")["score"].mean()

gender_score_mean

gender
female    83.00
male      83.25
Name: score, dtype: float64

In [11]:
csv_path = "week1_python_review/student_scores.csv"

df.to_csv(csv_path, index=False, encoding="utf-8-sig")

print("CSV 文件已保存到:", csv_path)

CSV 文件已保存到: week1_python_review/student_scores.csv

In [12]:
df_loaded = pd.read_csv("week1_python_review/student_scores.csv")

df_loaded

    name  gender  score  study_hours  passed
0    Tom    male     85            5    True
1  Jerry    male     90            6    True
2  Alice  female     78            3    True
3    Bob    male     92            7    True
4   Mike    male     66            2    True
5   Lucy  female     88            6    True

In [13]:
data_with_missing = {
    "name": ["Tom", "Jerry", "Alice", "Bob"],
    "score": [85, None, 78, 92],
    "study_hours": [5, 6, None, 7],
}

df_missing = pd.DataFrame(data_with_missing)

df_missing

    name  score  study_hours
0    Tom   85.0          5.0
1  Jerry    NaN          6.0
2  Alice   78.0          NaN
3    Bob   92.0          7.0

In [14]:
df_missing.isnull()

    name  score  study_hours
0  False  False        False
1  False   True        False
2  False  False         True
3  False  False        False

In [15]:
df_filled = df_missing.copy()

df_filled["score"] = df_filled["score"].fillna(df_filled["score"].mean())
df_filled["study_hours"] = df_filled["study_hours"].fillna(df_filled["study_hours"].mean())

df_filled

    name  score  study_hours
0    Tom   85.0          5.0
1  Jerry   85.0          6.0
2  Alice   78.0          6.0
3    Bob   92.0          7.0

In [16]:
# 相关性分析
correlation = df[["score", "study_hours"]].corr()

correlation

                score  study_hours
score        1.000000     0.966092
study_hours  0.966092     1.000000